name: Publish Docker Image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - version.txt
      - Dockerfile
      - .github/workflows/docker.yml
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Release Version
        id: release_version
        run: |
          app_version=$(sed -ne "s/APP_VERSION\s=\s'v\(.*\)'/\1/p" version.txt)
          echo "app_version=$app_version" >> $GITHUB_ENV

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:latest
            ${{ secrets.DOCKER_USERNAME }}/nas-tools:${{ env.app_version }}
